update: style-core (IDC@d08bfd1)
rhcpn/IRIS-Pages pull request #1
Opened 2022-01-17 01:01 UTC by ohmy04180

## 구분 ##
[ Issue(버그 픽스 포함) | Feature(이슈/버그 픽스 이외) ]

## 수정 내용  ##
- [x] update: style-core (IDC@d08bfd1)

##  이슈 링크  ##

##  관련 이미지  ## 

## TODO List ##
{ 후속또는 병행 머지 되어야 할 작업들 ( 디자인 작업등 )  }

2022-01-20 13:25 UTC, rhcpn requested changes
store 부분은 미처 개발 프레임워크에 넣지를 못했는데 ...

보통 모듈별로 store/module1, store/module2 같이 구성되는데
이때 vue 개발 모드로 hotupdate (실시간으로 화면에 반영되는거) 돌리기 위해 특정 선언을 하고나서 나머지 vuex 파일을 불러오는 구조를 취합니다.

ima의 main.js , analyzer.js 참고해주세요

2022-01-20 13:34 UTC, rhcpn approved these changes
코멘트만 확인해주시고 merge 해도 문제 없을것 같네요 ₩~~

2022-01-20 13:34 UTC, rhcpn commented on source/frontend/src/components/login.vue
> +<template lang="html">
메인 소스에 PR시 , 여럿이 작업하는 형태가 아니라면 기능이 일단락 된다음에 요청하는것이 좋을것 같습니다 ~~ 

현재는 뭐 일단 template에 가까운 기본형이라 특별한 코멘트는 없구요

2022-01-20 13:34 UTC, rhcpn commented on source/frontend/src/stories/Introduction.stories.mdx
> +import { Meta } from '@storybook/addon-docs';
해당 파일은 storybook에서 제공하는 코드와 설명을 조합해서 쓸수 있게 해주는 파일 포멧입니다.

https://storybook.js.org/docs/react/api/mdx
나중에 storybook 구성할때 참조해서 코드와 문서를 동시에 쓸수 있도록 위 링크 참조해주세요.

2022-02-04 01:12 UTC, rhcpn commented on source/frontend/src/modules/login/Login.vue
> +import LoginForm from "./components/login-form/login-form";
나중에 Vue Style 가이드의 파일명 규칙을 참고해보셔도 좋습니다.
https://kr.vuejs.org/v2/style-guide/index.html#%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%ED%8C%8C%EC%9D%BC-%EB%A7%A4%EC%9A%B0-%EC%B6%94%EC%B2%9C%ED%95%A8

2022-02-04 01:16 UTC, rhcpn commented on source/frontend/src/modules/login/components/login-form/login-form.vue
>  import RSA from "rsajs";
요거는 원래 로그인 할때 RSA 암호화 하는 부분인데요 .. login-form 이 컴포넌트 껍대기죠? 그렇다면 나중에 login.vue 에서 login-form에서 전달 받은 값을 암호화 하는 부분을 처리하도록 하는게 맞으니까 해당 부분은 정리하면 될것 같습니다.
RSA 사용 하는 부분은 전부 없애주세요 ~~

2022-02-04 01:16 UTC, rhcpn commented on source/frontend/src/modules/login/login.js
>  import * as Sentry from "@sentry/vue";
sentry 부분은 나중에 없애주세요
javascript 오류 나면 오류 수집 사이트로 보내는 기능인데 저희는 뭐 당장 필요없을것 같아요 ~~~

2022-02-04 01:17 UTC, rhcpn commented on source/frontend/src/modules/main/Main.vue
> +    <router-view></router-view>
별건 아니지만 해당 부분은 아래 링크 참조해주세요
https://kr.vuejs.org/v2/style-guide/index.html#%EC%85%80%ED%94%84-%ED%81%B4%EB%A1%9C%EC%A7%95-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%A7%A4%EC%9A%B0-%EC%B6%94%EC%B2%9C%ED%95%A8

2022-02-04 01:18 UTC, rhcpn commented on source/frontend/src/modules/main/main.js
>  import * as Sentry from "@sentry/vue";
여기도 마찬가지로 나중에 없애주세요 ~

2022-02-04 01:18 UTC, rhcpn commented on source/frontend/src/modules/main/main.js
>  import { Integrations } from "@sentry/tracing";
요것도 ~

2022-02-04 05:20 UTC, ohmy04180 commented on source/frontend/src/modules/login/login.js
>  import * as Sentry from "@sentry/vue";
반영 완료

2022-02-04 05:20 UTC, ohmy04180 commented on source/frontend/src/modules/login/Login.vue
> +import LoginForm from "./components/login-form/login-form";
반영 완료

2022-02-04 05:20 UTC, ohmy04180 commented on source/frontend/src/modules/main/Main.vue
> +    <router-view></router-view>
반영 완료

2022-02-04 05:20 UTC, ohmy04180 commented on source/frontend/src/modules/main/main.js
>  import * as Sentry from "@sentry/vue";
반영 완료

2022-02-04 05:20 UTC, ohmy04180 commented on source/frontend/src/modules/main/main.js
>  import { Integrations } from "@sentry/tracing";
반영 완료

2022-02-04 06:56 UTC, ohmy04180 commented on source/frontend/src/modules/login/components/login-form/login-form.vue
>  import RSA from "rsajs";
RSA 관련 코드를 지우니 에러가 발생하는데, 작업 하면서 해당 부분 수정을 할까요?
![image](https://user-images.githubusercontent.com/64238814/152485526-1d8f6a81-58f8-4cbe-846c-a528d355f0f4.png)

2022-02-04 09:17 UTC, rhcpn commented on source/frontend/src/modules/login/components/login-form/login-form.vue
>  import RSA from "rsajs";
구두로 전달한 대로 submit () 메소드만 남겨두고 버튼에 해당 메소드를 걸어두고 내용은 싹지우고 emit 관련 코드를 넣고 나머지 method 는 다 지우면 될것 같네요

2022-02-04 09:19 UTC, rhcpn commented on source/frontend/src/modules/main/views/Views.vue
> +import ReportScreen from "./components/report-screen/report-screen";
나중에 ./components 경로가 길면 @comp 라던지 하는 alias 선언을 해보셔도 좋습니다.

2022-02-04 09:21 UTC, rhcpn commented on source/frontend/src/store/login.js
> +
login 부분은 기능이 비교적 단순해서 .. store 가 굳이 필요 없을수도 있는데 검토해주세요

2022-02-04 09:21 UTC, rhcpn commented on source/frontend/src/store/login/enter.js
> +export default enter;
login 부분에 store 처리가 필요할지 검토해주세요 ~

2022-02-04 09:22 UTC, rhcpn commented on source/frontend/src/store/views.js
> +import Vue from "vue";
해당 파일을 만드는 기준은 모듈 하나로 보시면 될것 같습니다.
views 가 모듈은 아니고 
main 모듈에서 페이지 역할이면 해당 파일은 없애고 main 쪽 store 하위로 가는게 맞겠네요

2022-02-04 09:24 UTC, rhcpn commented on source/frontend/src/store/views/slideshow.js
> +const slideshow = {
위에서 말한것에 연장선상인데요 컴포넌트 당 무조건 store를 만드는게 아니고
어떤 데이터 흐름상의 프로세스를 담당하는 개념으로 보시고
store 하나를 여러개의 컴포넌트가 공유하는 것 쯤으로 보시면 될것 같아요 ~~

2022-02-07 05:31 UTC, ohmy04180 commented on source/frontend/src/modules/main/views/Views.vue
> +import ReportScreen from "./components/report-screen/report-screen";
반영 완료

2022-02-07 05:31 UTC, ohmy04180 commented on source/frontend/src/store/login.js
> +
반영 완료

2022-02-07 05:31 UTC, ohmy04180 commented on source/frontend/src/store/login/enter.js
> +export default enter;
반영 완료

2022-02-07 09:27 UTC, rhcpn commented on source/frontend/src/modules/login/components/login-form/login-form.vue
> +          maxlength="15"
이건 나중에 property로 빼서 연동해주세요 ㅎㅎ

2022-02-07 09:27 UTC, rhcpn commented on source/frontend/src/modules/login/components/login-form/login-form.vue
> +          maxlength="10"
property로 빼주세요 ~~ 나중에

2022-02-07 09:28 UTC, rhcpn commented on source/frontend/src/modules/login/components/login-form/login-form.vue
> +      <select id="locale" class="login_form-locale">
해당 부분은 나중에 로케일 변경 시, 서버 및 UI 쪽에서 로케일 변경을 해야 하니까 이벤트 처리를 추가해야 겠네요 ~

2022-02-07 09:32 UTC, rhcpn approved these changes
일단 해당 코드들은 merge 하겠습니다.
comment 잘 확인해주시고

API 연동 전에 우선 화면상에서 테스트 데이터로 동작 하도록 구성 하고 나서
API를 실제 연동 하는 방법으로 진행 할까합니다.

우선 필요한것이 보고서 리스트 샘플이 있어야 겠네요 
이것은 일단 제가 샘플로 만들어서 드릴께요
해당 리스트를 코드상에서 가져다가 우선 화면 동작하게 만들어 보시죠 ~~

2022-02-07 09:32 UTC, merged